### ISSUE TITLE
Unable to deploy environment on Windows: ERROR    -> SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)

### ISSUE THREAD

**Issue by igalic** [adrienthebo/r10k#1238]
## Describe the Bug

When trying to deploy and environment on Windows I'm (now?) getting:

```
PS C:\ProgramData\PuppetLabs\code\environments> & 'C:\Program Files\Puppet Labs\Puppet\puppet\bin\r10k.bat' --config C:\ProgramData\PuppetLabs\r10k\etc\r10k.yaml deploy environment --verbose --puppetfile
INFO     -> Deploying environment C:/ProgramData/PuppetLabs/code/environments/production
INFO     -> Environment production is now at 3fbc3b3d63414588ca8a4aba633af5ab108ffcde
INFO     -> Using Puppetfile 'C:/ProgramData/PuppetLabs/code/environments/production/Puppetfile'
INFO     -> Deploying module to C:/ProgramData/PuppetLabs/code/environments/production/modules/inifile
INFO     -> Deploying module to C:/ProgramData/PuppetLabs/code/environments/production/modules/acl
INFO     -> Deploying module to C:/ProgramData/PuppetLabs/code/environments/production/modules/registry
INFO     -> Deploying module to C:/ProgramData/PuppetLabs/code/environments/production/modules/stdlib
ERROR    -> SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)
ERROR    -> SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)
PS C:\ProgramData\PuppetLabs\code\environments>
```

(i'll put a `--trace` run below)

## Expected Behavior

I'd rather this didn't happen…

## Steps to Reproduce

```powershell
& 'C:\Program Files\Puppet Labs\Puppet\puppet\bin\r10k.bat' --config C:\ProgramData\PuppetLabs\r10k\etc\r10k.yaml deploy environment --verbose --puppetfile
```

This behaviour seems to be either intermittent, or triggered by a sudden unexplainable change.
I'll try to figure out if it happens on a fresh machine, and then I'll have a full (and very minimal) PowerShell script to reproduce it fully here.

## Environment
 - Version 3.13.0 (installed via gem)
 - Platform Windows Server 2019 Datacenter

## Additional Context

<details><summary>same run as above, but with <code>--trace</code></summary>

```
PS C:\ProgramData\PuppetLabs\code\environments> & 'C:\Program Files\Puppet Labs\Puppet\puppet\bin\r10k.bat' --trace --config C:\ProgramData\PuppetLabs\r10k\etc\r10k.yaml deploy environment --verbose --puppetfile
INFO     -> Deploying environment C:/ProgramData/PuppetLabs/code/environments/production
INFO     -> Environment production is now at 3fbc3b3d63414588ca8a4aba633af5ab108ffcde
INFO     -> Using Puppetfile 'C:/ProgramData/PuppetLabs/code/environments/production/Puppetfile'
INFO     -> Deploying module to C:/ProgramData/PuppetLabs/code/environments/production/modules/acl
INFO     -> Deploying module to C:/ProgramData/PuppetLabs/code/environments/production/modules/inifile
INFO     -> Deploying module to C:/ProgramData/PuppetLabs/code/environments/production/modules/stdlib
INFO     -> Deploying module to C:/ProgramData/PuppetLabs/code/environments/production/modules/registry
ERROR    -> SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/2.7.0/net/protocol.rb:44:in `connect_nonblock'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/2.7.0/net/protocol.rb:44:in `ssl_socket_connect'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/2.7.0/net/http.rb:1009:in `connect'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/2.7.0/net/http.rb:932:in `start'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/2.7.0/net/http.rb:1483:in `request'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/2.7.0/net/http.rb:1241:in `get'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/faraday-0.17.4/lib/faraday/adapter/net_http.rb:86:in `perform_request'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/faraday-0.17.4/lib/faraday/adapter/net_http.rb:44:in `block in call'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/faraday-0.17.4/lib/faraday/adapter/net_http.rb:93:in `with_net_http_connection'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/faraday-0.17.4/lib/faraday/adapter/net_http.rb:39:in `call'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/puppet_forge-2.3.4/lib/puppet_forge/connection/connection_failure.rb:9:in `call'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/faraday-0.17.4/lib/faraday/response.rb:8:in `call'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/faraday_middleware-0.14.0/lib/faraday_middleware/response_middleware.rb:31:in `call'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/puppet_forge-2.3.4/lib/puppet_forge/middleware/symbolify_json.rb:64:in `call'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/faraday-0.17.4/lib/faraday/rack_builder.rb:143:in `build_response'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/faraday-0.17.4/lib/faraday/connection.rb:387:in `run_request'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/faraday-0.17.4/lib/faraday/connection.rb:138:in `get'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/puppet_forge-2.3.4/lib/puppet_forge/v3/base.rb:69:in `request'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/puppet_forge-2.3.4/lib/puppet_forge/lazy_accessors.rb:85:in `fetch'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/r10k-3.13.0/lib/r10k/module/forge.rb:128:in `deprecated?'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/r10k-3.13.0/lib/r10k/module/forge.rb:175:in `install'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/r10k-3.13.0/lib/r10k/module/forge.rb:69:in `sync'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/r10k-3.13.0/lib/r10k/content_synchronizer.rb:82:in `block (2 levels) in sync_thread'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/r10k-3.13.0/lib/r10k/content_synchronizer.rb:81:in `each'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/r10k-3.13.0/lib/r10k/content_synchronizer.rb:81:in `block in sync_thread'
ERROR    -> SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/2.7.0/net/protocol.rb:44:in `connect_nonblock'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/2.7.0/net/protocol.rb:44:in `ssl_socket_connect'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/2.7.0/net/http.rb:1009:in `connect'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/2.7.0/net/http.rb:932:in `start'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/2.7.0/net/http.rb:1483:in `request'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/2.7.0/net/http.rb:1241:in `get'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/faraday-0.17.4/lib/faraday/adapter/net_http.rb:86:in `perform_request'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/faraday-0.17.4/lib/faraday/adapter/net_http.rb:44:in `block in call'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/faraday-0.17.4/lib/faraday/adapter/net_http.rb:93:in `with_net_http_connection'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/faraday-0.17.4/lib/faraday/adapter/net_http.rb:39:in `call'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/puppet_forge-2.3.4/lib/puppet_forge/connection/connection_failure.rb:9:in `call'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/faraday-0.17.4/lib/faraday/response.rb:8:in `call'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/faraday_middleware-0.14.0/lib/faraday_middleware/response_middleware.rb:31:in `call'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/puppet_forge-2.3.4/lib/puppet_forge/middleware/symbolify_json.rb:64:in `call'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/faraday-0.17.4/lib/faraday/rack_builder.rb:143:in `build_response'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/faraday-0.17.4/lib/faraday/connection.rb:387:in `run_request'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/faraday-0.17.4/lib/faraday/connection.rb:138:in `get'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/puppet_forge-2.3.4/lib/puppet_forge/v3/base.rb:69:in `request'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/puppet_forge-2.3.4/lib/puppet_forge/lazy_accessors.rb:85:in `fetch'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/r10k-3.13.0/lib/r10k/module/forge.rb:128:in `deprecated?'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/r10k-3.13.0/lib/r10k/module/forge.rb:175:in `install'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/r10k-3.13.0/lib/r10k/module/forge.rb:69:in `sync'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/r10k-3.13.0/lib/r10k/content_synchronizer.rb:82:in `block (2 levels) in sync_thread'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/r10k-3.13.0/lib/r10k/content_synchronizer.rb:81:in `each'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/r10k-3.13.0/lib/r10k/content_synchronizer.rb:81:in `block in sync_thread'
PS C:\ProgramData\PuppetLabs\code\environments>
```

</details>

**Comment by igalic** [comment]
can repro on fresh install:

```
PS C:\Windows\system32>  & $r10k --config $r10k_yaml_path deploy environment --verbose --puppetfile
INFO     -> Deploying environment C:/ProgramData/PuppetLabs/code/environments/production
INFO     -> Environment production is now at 5b5fca36f42ce44b173080e1ca84f2ccf20c94c1
INFO     -> Using Puppetfile 'C:/ProgramData/PuppetLabs/code/environments/production/Puppetfile'
INFO     -> Deploying module to C:/ProgramData/PuppetLabs/code/environments/production/modules/stdlib
INFO     -> Deploying module to C:/ProgramData/PuppetLabs/code/environments/production/modules/acl
INFO     -> Deploying module to C:/ProgramData/PuppetLabs/code/environments/production/modules/registry
INFO     -> Deploying module to C:/ProgramData/PuppetLabs/code/environments/production/modules/inifile
ERROR    -> SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)
#<Thread:0x00000000072da260 C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/2.7.0/open3.rb:287 run> terminated with exception (report_on_exception is true):
#<Thread:0x00000000072da148 C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/2.7.0/open3.rb:288 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        1: from C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/2.7.0/open3.rb:288:in `block (2 levels) in capture3'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/2.7.0/open3.rb:288:in `read': closed stream (IOError)
Traceback (most recent call last):
        1: from C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/2.7.0/open3.rb:287:in `block (2 levels) in capture3'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/2.7.0/open3.rb:287:in `read': closed stream (IOError)
ERROR    -> SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)
PS C:\Windows\system32> ls -l C:\ProgramData\PuppetLabs\code\environments\production\
```

Here's the PowerShell to repro:

```powershell
# Chocolatey.org install script expanded:
Set-ExecutionPolicy Bypass -Scope Process -Force;
[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

# reload path:
$env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")

choco feature enable -n allowGlobalConfirmation

# Install Git, Firefox (a usable browser) and puppet-agent
# We'll use Puppet Agent's Ruby to install r10k
choco install git.install -y --params "/GitAndUnixToolsOnPath"
choco install -y firefox puppet-agent

$env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")

# Call git's refreshenv
refreshenv

$PuppetPath = 'C:\Program Files\Puppet Labs\Puppet\puppet\bin'
$gem = Join-Path $PuppetPath -ChildPath "gem.bat"
$r10k = Join-Path $PuppetPath -ChildPath "r10k.bat"

& $gem install r10k

$r10k_yaml = @"
---
:sources:
  puppet:
    basedir: "C:/ProgramData/PuppetLabs/code/environments"
    remote: "https://codeberg.org/meena-co/puppet-environment.git"
"@

$r10k_yaml_path = "C:\ProgramData\PuppetLabs\r10k\etc\r10k.yaml"

New-Item -Path $(Split-Path $r10k_yaml_path) -ItemType Directory -Force
echo $r10k_yaml |  % {$_ -replace "`r", ""} | Set-Content -Path $r10k_yaml_path -NoNewline

ssh -o "StrictHostkeyChecking no" git@codeberg.org
& $r10k --config $r10k_yaml_path deploy environment --verbose --puppetfile

# now install bolt, too:
choco install -y puppet-bolt
```

i have no idea what's going on, cuz I'm pretty sure this worked last week, Friday (29th of Oct, 2021)
And we haven't had a new release since then. I was on the last release then!

Also, since I don't know how to strace or dtrace or whatnot on Windows, I have no idea how to debug this, short of installing pry

**Comment by igalic** [comment]
as an aside:

trying to install modules with puppet itself:

```powershell
PS C:\ProgramData\PuppetLabs\r10k\etc> puppet module install puppetlabs/stdlib
Notice: Preparing to install into C:/ProgramData/PuppetLabs/code/environments/production/site:modules:C:/ProgramData/PuppetLabs/code/modules ...
Error: Invalid argument @ dir_s_mkdir - C:/ProgramData/PuppetLabs/code/environments/production/site:modules:C:
Error: Try 'puppet help module install' for usage
PS C:\ProgramData\PuppetLabs\r10k\etc>
```

😭 

___________
at least this can be disregarded: environment.conf on windows needs to use `;` instead of `:` for separators.

**Comment by igalic** [comment]
i have dug deeper!

here's our openssl:

```powershell
PS C:\Program Files\Puppet Labs\Puppet> puppet\bin\openssl.exe s_client -verify_hostname forge.puppet.com -verify_depth 4 -nocommands -quiet -servername forge.puppet.com  -connect forge.puppet.com:443
depth=1 C = FR, ST = Paris, L = Paris, O = Gandi, CN = Gandi Standard SSL CA 2
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = forge.puppet.com
verify return:1
get /
HTTP/1.1 400 Bad request
content-length: 90
cache-control: no-cache
content-type: text/html
connection: close

<html><body><h1>400 Bad request</h1>
Your browser sent an invalid request.
</body></html>
PS C:\Program Files\Puppet Labs\Puppet>
```

here's git's openssl:

```powershell
PS C:\Program Files\Puppet Labs\Puppet> openssl.exe s_client -verify_hostname forge.puppet.com -verify_depth 4 -nocommands -quiet -servername forge.puppet.com -connect forge.puppet.com:443
depth=2 C = US, ST = New Jersey, L = Jersey City, O = The USERTRUST Network, CN = USERTrust RSA Certification Authority
verify return:1
depth=1 C = FR, ST = Paris, L = Paris, O = Gandi, CN = Gandi Standard SSL CA 2
verify return:1
depth=0 CN = forge.puppet.com
verify return:1
get /
HTTP/1.1 400 Bad request
content-length: 90
cache-control: no-cache
content-type: text/html
connection: close

<html><body><h1>400 Bad request</h1>
Your browser sent an invalid request.
</body></html>
PS C:\Program Files\Puppet Labs\Puppet>
```

(works!)

here's git OpenSSL with our CAfile:

```powershell
PS C:\Program Files\Puppet Labs\Puppet> openssl.exe s_client -verify_hostname forge.puppet.com -verify_depth 4 -nocommands -quiet -servername forge.puppet.com -CAfile 'puppet\\ssl\cert.pem' -connect forge.puppet.com:4
43
depth=2 C = US, ST = New Jersey, L = Jersey City, O = The USERTRUST Network, CN = USERTrust RSA Certification Authority
verify return:1
depth=1 C = FR, ST = Paris, L = Paris, O = Gandi, CN = Gandi Standard SSL CA 2
verify return:1
depth=0 CN = forge.puppet.com
verify return:1
get /
HTTP/1.1 400 Bad request
content-length: 90
cache-control: no-cache
content-type: text/html
connection: close

<html><body><h1>400 Bad request</h1>
Your browser sent an invalid request.
</body></html>
PS C:\Program Files\Puppet Labs\Puppet>
```

(works??)

here's our openssl with our own CAfile:

```powershell
PS C:\Program Files\Puppet Labs\Puppet> puppet\bin\openssl.exe s_client -verify_hostname forge.puppet.com -verify_depth 4 -nocommands -quiet -servername forge.puppet.com -CAfile 'puppet\ssl\cert.pem' -connect forge.pu
ppet.com:443
depth=2 C = US, ST = New Jersey, L = Jersey City, O = The USERTRUST Network, CN = USERTrust RSA Certification Authority
verify return:1
depth=1 C = FR, ST = Paris, L = Paris, O = Gandi, CN = Gandi Standard SSL CA 2
verify return:1
depth=0 CN = forge.puppet.com
verify return:1
get /
HTTP/1.1 400 Bad request
content-length: 90
cache-control: no-cache
content-type: text/html
connection: close

<html><body><h1>400 Bad request</h1>
Your browser sent an invalid request.
</body></html>
PS C:\Program Files\Puppet Labs\Puppet>
```

works.

so, why doesn't it work out of the box, like git's openssl?

i have no idea (how to strace / dtrace on windows, so i don't know)

**Comment by igalic** [comment]
so! installed sysinternals and started procmon

![image](https://user-images.githubusercontent.com/497249/140174536-d2054690-e3fa-4ef4-959e-550d5311408c.png)

it looks like our [base dir config](https://github.com/puppetlabs/puppet-agent/blob/4a99fb02cb9c5617a1ce2f639292c798a51b42c1/resources/files/windows/environment.bat#L24-L25) is wrong somehow.

**Comment by igalic** [comment]
I think this boils down to

> it looks like our [base dir config](https://github.com/puppetlabs/puppet-agent/blob/4a99fb02cb9c5617a1ce2f639292c798a51b42c1/resources/files/windows/environment.bat#L24-L25) is wrong somehow.

yesno. During build we should be using something [`COMMONPROGRAMFILES`](https://docs.microsoft.com/en-us/windows/deployment/usmt/usmt-recognized-environment-variables) but if that is resolved on a system using English as its language end up with the wrong path for systems except English.

another issue is that the above environment.bat is only used in Puppet/bin/ but not in Puppet/puppet/bin

and even then, that won't affect binaries installed via `gem install`

the simplest solution might be to package r10k for chocolatey and other systems.

**Comment by mwaggett** [comment]
Hi @igalic, thanks for opening this! r10k is now considered to be feature complete and we are unfortunately discontinuing development. As a result, we are closing all open issues and pull requests. I sincerely apologize that we’re unable to address this issue.

**Comment by bastelfreak** [comment]
@Magisus why do you massclose valid issues? If Puppet has no interest in working on it, that's one thing, but why closing the issues?
