### ISSUE TITLE
Incompatible with Ruby 3.0

### ISSUE THREAD

**Issue by tambry** [adrienthebo/r10k#1266]
## Describe the Bug
r10k 3.14.0 doesn't work with the Rugged Git provider with CRuby 3.0 shipped in Debian Unstable. Running manually using CRuby 2.7 works.

## Steps to Reproduce
1. Rugged Git source.
2. `/usr/bin/r10k deploy environment --modules`

```
root@deb:/etc/ssl# /usr/bin/r10k deploy environment --modules --trace
ERROR    -> Unable to determine current branches for Git source 'dev' (/etc/puppet/code/environments)
/usr/share/rubygems-integration/all/gems/r10k-3.14.0/lib/r10k/source/git.rb:74:in `preload!'
/usr/share/rubygems-integration/all/gems/r10k-3.14.0/lib/r10k/deployment.rb:36:in `each'
/usr/share/rubygems-integration/all/gems/r10k-3.14.0/lib/r10k/deployment.rb:36:in `preload!'
/usr/share/rubygems-integration/all/gems/r10k-3.14.0/lib/r10k/action/deploy/environment.rb:109:in `visit_deployment'
/usr/share/rubygems-integration/all/gems/r10k-3.14.0/lib/r10k/action/visitor.rb:27:in `visit'
/usr/share/rubygems-integration/all/gems/r10k-3.14.0/lib/r10k/deployment.rb:106:in `accept'
/usr/share/rubygems-integration/all/gems/r10k-3.14.0/lib/r10k/action/deploy/environment.rb:75:in `call'
/usr/share/rubygems-integration/all/gems/r10k-3.14.0/lib/r10k/action/runner.rb:33:in `call'
/usr/share/rubygems-integration/all/gems/r10k-3.14.0/lib/r10k/action/cri_runner.rb:67:in `call'
/usr/lib/ruby/vendor_ruby/cri/command_dsl.rb:294:in `block in runner'
/usr/lib/ruby/vendor_ruby/cri/command.rb:362:in `run_this'
/usr/lib/ruby/vendor_ruby/cri/command.rb:298:in `run'
/usr/lib/ruby/vendor_ruby/cri/command.rb:316:in `run'
/usr/lib/ruby/vendor_ruby/cri/command.rb:316:in `run'
/usr/share/rubygems-integration/all/gems/r10k-3.14.0/bin/r10k:7:in `<top (required)>'
/usr/bin/r10k:25:in `load'
/usr/bin/r10k:25:in `<main>'
Original exception:
wrong number of arguments (given 2, expected 0..1)
/usr/lib/x86_64-linux-gnu/rubygems-integration/3.0.0/gems/rugged-1.2.0/lib/rugged/repository.rb:257:in `fetch'
/usr/lib/x86_64-linux-gnu/rubygems-integration/3.0.0/gems/rugged-1.2.0/lib/rugged/repository.rb:257:in `fetch'
/usr/share/rubygems-integration/all/gems/r10k-3.14.0/lib/r10k/git/rugged/bare_repository.rb:67:in `block (2 levels) in fetch'
/usr/share/rubygems-integration/all/gems/r10k-3.14.0/lib/r10k/git/rugged/base_repository.rb:78:in `with_repo'
/usr/share/rubygems-integration/all/gems/r10k-3.14.0/lib/r10k/git/rugged/bare_repository.rb:67:in `block in fetch'
/usr/share/rubygems-integration/all/gems/r10k-3.14.0/lib/r10k/git.rb:192:in `with_proxy'
/usr/share/rubygems-integration/all/gems/r10k-3.14.0/lib/r10k/git/rugged/bare_repository.rb:66:in `fetch'
/usr/share/rubygems-integration/all/gems/r10k-3.14.0/lib/r10k/git/cache.rb:84:in `sync!'
/usr/share/rubygems-integration/all/gems/r10k-3.14.0/lib/r10k/git/rugged/cache.rb:17:in `sync!'
/usr/share/rubygems-integration/all/gems/r10k-3.14.0/lib/r10k/git/cache.rb:73:in `sync'
/usr/share/rubygems-integration/all/gems/r10k-3.14.0/lib/r10k/source/git.rb:76:in `preload!'
/usr/share/rubygems-integration/all/gems/r10k-3.14.0/lib/r10k/deployment.rb:36:in `each'
/usr/share/rubygems-integration/all/gems/r10k-3.14.0/lib/r10k/deployment.rb:36:in `preload!'
/usr/share/rubygems-integration/all/gems/r10k-3.14.0/lib/r10k/action/deploy/environment.rb:109:in `visit_deployment'
/usr/share/rubygems-integration/all/gems/r10k-3.14.0/lib/r10k/action/visitor.rb:27:in `visit'
/usr/share/rubygems-integration/all/gems/r10k-3.14.0/lib/r10k/deployment.rb:106:in `accept'
/usr/share/rubygems-integration/all/gems/r10k-3.14.0/lib/r10k/action/deploy/environment.rb:75:in `call'
/usr/share/rubygems-integration/all/gems/r10k-3.14.0/lib/r10k/action/runner.rb:33:in `call'
/usr/share/rubygems-integration/all/gems/r10k-3.14.0/lib/r10k/action/cri_runner.rb:67:in `call'
/usr/lib/ruby/vendor_ruby/cri/command_dsl.rb:294:in `block in runner'
/usr/lib/ruby/vendor_ruby/cri/command.rb:362:in `run_this'
/usr/lib/ruby/vendor_ruby/cri/command.rb:298:in `run'
/usr/lib/ruby/vendor_ruby/cri/command.rb:316:in `run'
/usr/lib/ruby/vendor_ruby/cri/command.rb:316:in `run'
/usr/share/rubygems-integration/all/gems/r10k-3.14.0/bin/r10k:7:in `<top (required)>'
/usr/bin/r10k:25:in `load'
/usr/bin/r10k:25:in `<main>'
```

## Environment
 - **Version**: 3.14.0
 - **Platform**: Debian Unstable

**Comment by Magisus** [comment]
I don't think we really expect r10k 3.x to work on Ruby 3; we don't test on it currently. Did you ever have it working, or is this the first time you've tried?

**Comment by tambry** [comment]
Looking at master this actually seems to have been fixed by a26de6714b3a5a2484d4ae14e7ef326dfbf7d1bf. Confirmed locally as working.

**Comment by Magisus** [comment]
Yeah I just found that too :) We can get a release out with that commit if that helps (and at that point maybe we can add 3.0 to the test matrix for main too).

**Comment by tambry** [comment]
A release just for me isn't necessary as I can apply the change locally. Take it at your own pace. 🙂
