### ISSUE TITLE
svn doesn't work any more

### ISSUE THREAD

**Issue by robert-cam** [adrienthebo/r10k#1305]
I'm using svn with r10k and we're stuck on version 3.9.0 as anything newer gives the error "R10K::Source::SVN cannot handle option 'overrides'". A basic r10k.yaml with "type: svn" is enough to trigger it:

```
---
sources:
  puppet:
    type: svn
    remote: 'http://localhost/svn/puppet'
    basedir: '/etc/puppetlabs/code/environments'
```
This config works with 3.9.0.

Here's a trace from 3.15.0:
```
# r10k  -c r10k.yaml  deploy environment --verbose debug2 -t
[2022-04-29 11:13:18 - DEBUG2] Reading configuration from "r10k.yaml"
[2022-04-29 11:13:18 - DEBUG1] Testing to see if feature pe_license is available.
[2022-04-29 11:13:18 - DEBUG2] Attempting to load library 'pe_license' for feature pe_license
[2022-04-29 11:13:18 - DEBUG2] Error while loading library pe_license for feature pe_license: cannot load such file -- pe_license
[2022-04-29 11:13:18 - DEBUG1] Feature pe_license is not available.
[2022-04-29 11:13:18 - DEBUG2] pe_license feature is not available, PE only Puppet modules will not be downloadable.
[2022-04-29 11:13:18 - ERROR] R10K::Source::SVN cannot handle option 'overrides'
/usr/local/share/gems/gems/r10k-3.15.0/lib/r10k/util/setopts.rb:69:in `block in setopts'
/usr/local/share/gems/gems/r10k-3.15.0/lib/r10k/util/setopts.rb:42:in `each_pair'
/usr/local/share/gems/gems/r10k-3.15.0/lib/r10k/util/setopts.rb:42:in `setopts'
/usr/local/share/gems/gems/r10k-3.15.0/lib/r10k/source/svn.rb:62:in `initialize'
/usr/local/share/gems/gems/r10k-3.15.0/lib/r10k/keyed_factory.rb:30:in `new'
/usr/local/share/gems/gems/r10k-3.15.0/lib/r10k/keyed_factory.rb:30:in `generate'
/usr/local/share/gems/gems/r10k-3.15.0/lib/r10k/source.rb:20:in `generate'
/usr/local/share/gems/gems/r10k-3.15.0/lib/r10k/source.rb:31:in `from_hash'
/usr/local/share/gems/gems/r10k-3.15.0/lib/r10k/deployment.rb:121:in `block in load_sources'
/usr/local/share/gems/gems/r10k-3.15.0/lib/r10k/deployment.rb:120:in `each'
/usr/local/share/gems/gems/r10k-3.15.0/lib/r10k/deployment.rb:120:in `map'
/usr/local/share/gems/gems/r10k-3.15.0/lib/r10k/deployment.rb:120:in `load_sources'
/usr/local/share/gems/gems/r10k-3.15.0/lib/r10k/deployment.rb:48:in `sources'
/usr/local/share/gems/gems/r10k-3.15.0/lib/r10k/deployment.rb:36:in `preload!'
/usr/local/share/gems/gems/r10k-3.15.0/lib/r10k/action/deploy/environment.rb:109:in `visit_deployment'
/usr/local/share/gems/gems/r10k-3.15.0/lib/r10k/action/visitor.rb:27:in `visit'
/usr/local/share/gems/gems/r10k-3.15.0/lib/r10k/deployment.rb:106:in `accept'
/usr/local/share/gems/gems/r10k-3.15.0/lib/r10k/action/deploy/environment.rb:75:in `call'
/usr/local/share/gems/gems/r10k-3.15.0/lib/r10k/action/runner.rb:33:in `call'
/usr/local/share/gems/gems/r10k-3.15.0/lib/r10k/action/cri_runner.rb:67:in `call'
/usr/local/share/gems/gems/cri-2.15.11/lib/cri/command_dsl.rb:294:in `block in runner'
/usr/local/share/gems/gems/cri-2.15.11/lib/cri/command.rb:362:in `run_this'
/usr/local/share/gems/gems/cri-2.15.11/lib/cri/command.rb:298:in `run'
/usr/local/share/gems/gems/cri-2.15.11/lib/cri/command.rb:316:in `run'
/usr/local/share/gems/gems/cri-2.15.11/lib/cri/command.rb:316:in `run'
/usr/local/share/gems/gems/r10k-3.15.0/bin/r10k:7:in `<top (required)>'
/usr/local/bin/r10k:23:in `load'
/usr/local/bin/r10k:23:in `<main>'
```

**Comment by Magisus** [comment]
Thanks for reporting this!

**Comment by robert-cam** [comment]
We'd still like to see this fixed so we can upgrade r10k.

**Comment by drkp** [comment]
This is still an issue...
